apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx      #label to identity
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx    #pod with this label will manage
  template:
    metadata:
      labels:
        app: nginx        # must match selector
    spec:
      containers:
        - name: nginx           #container name
          image: nginx:latest    #official image
          resources:
      limits:
        memory: 512Mi
        cpu: "1"
      requests:
        memory: 256Mi
        cpu: "0.2"
        ports:
          - containerPort: 80
